### ISSUE TITLE
Any reason as to why the runnable JAR (console.zip) is missing among the downloadable assets?

### ISSUE THREAD

**Issue by cdcurry** [oracle/weblogic-remote-console#69]
Console.zip last appeared as downloadable asset in Release 2.4.5, but not in later versions.
Is it being deprecated or do we just have to build it ourselves?

**Comment by lfeigen** [comment]
Yes, we deliberately decided to stop including console.zip.  One uses the console.zip in order to execute "java -jar console.jar".  Given that the endpoint created by such does not meet our standards for being a "server", we see this as only practical for testing and, therefore, building one's self is reasonable.

**Comment by cdcurry** [comment]
Thanks for the clarification.
